version: "3"

services:
  web:
    image: local/php:apache-plus
    container_name: web
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    networks:
      - app-network
    ports:
      - 8080:80
    volumes:
      - ./src/:/var/www/html/
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - app-network
    ports:
      - 33060:3306
    volumes:
      - dbdata:/var/lib/mysql
      - dblog:/var/log/mysql

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
  dblog:
    driver: local
